sudo: false
language: node_js
node_js:
- '4.0'
- iojs
- '0.12'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
  code_climate:
    repo_token: $CODECLIMATE_REPO_TOKEN
before_install:
- npm install -g npm
- npm install -g node-gyp
- npm install -g codeclimate-test-reporter
- node-gyp clean
after_script:
- codeclimate-test-reporter < coverage/lcov.info
install:
- export CXX=g++-4.8
- $CXX --version
- npm install
script:
- NODE_ENV=test npm run coverage
- NODE_ENV=test npm run lint
env:
  global:
    secure: dXctKKVIIYN7b2LDvj5ZV9FUdxZ5TmfddO1G5s6pRWVukEejMYe1wEHomoYnBNlGjG3J4V8GSNcx1eYCF7QuePH8FIR8ACpVIae9MgY9awUWMRMuGaN70qZKtBL74nY3aGzlh0bhXxlvMwDTo/vTR0nWbxnOQyT/ksRVkyEBdNc=
